import PDFDocument from "pdfkit";
export function buildCommitmentProofPdf({org,client,commitment,events}){
  const doc=new PDFDocument({margin:40});
  doc.fontSize(18).text(org?.name||"NOOLIX");
  doc.moveDown(0.5);
  doc.fontSize(14).text("Proof of Approval & Acceptance");
  doc.moveDown();
  doc.fontSize(12).text(`Client: ${client?.name||"-"} (${client?.email||"-"})`);
  doc.text(`Commitment: ${commitment.title}`);
  doc.text(`Status: ${commitment.status}`);
  doc.text(`Version: ${commitment.version}`);
  doc.moveDown();
  doc.fontSize(12).text("Scope:",{underline:true}); doc.moveDown(0.25);
  doc.fontSize(11).text(commitment.scopeText||"-"); doc.moveDown();
  doc.fontSize(12).text("Timeline:",{underline:true}); doc.moveDown(0.25);
  for(const e of (events||[])){ doc.fontSize(10).text(`${new Date(e.createdAt).toISOString()} — ${e.type}${e.message? " — "+e.message:""}`); }
  doc.moveDown(); doc.fontSize(9).text("Generated by NOOLIX",{align:"right"});
  doc.end(); return doc;
}
