import { Router } from "express";
import { asyncHandler } from "../utils/asyncHandler.js";
import { requireAuth } from "../middleware/requireAuth.js";
import { authorizeFeature } from "../middleware/authorizeFeature.js";
import { authorizeCommitmentAccess } from "../middleware/authorizeResource.js";
import { validate } from "../middleware/validate.js";
import { FEATURES } from "../constants/features.js";
import { createCommitmentSchema, listCommitmentsSchema, updateCommitmentSchema, assignCommitmentSchema } from "../validators/commitment.schema.js";
import { listChangeRequestsSchema, acceptChangeRequestSchema, rejectChangeRequestSchema } from "../validators/changeRequest.schema.js";
import { createOne, list, getOne, updateOne, assign, markDeliveredCtrl, sendApproval, resendApproval, sendAcceptance, resendAcceptance, history, listChangeRequestsCtrl, acceptChangeRequestCtrl, rejectChangeRequestCtrl } from "../controllers/commitments.controller.js";
export const commitmentsRouter=Router();
commitmentsRouter.post("/", requireAuth, validate(createCommitmentSchema), asyncHandler(createOne));
commitmentsRouter.get("/", requireAuth, validate(listCommitmentsSchema), asyncHandler(list));
commitmentsRouter.get("/:id", requireAuth, asyncHandler(authorizeCommitmentAccess), asyncHandler(getOne));
commitmentsRouter.patch("/:id", requireAuth, validate(updateCommitmentSchema), asyncHandler(updateOne));
commitmentsRouter.patch("/:id/assign", requireAuth, authorizeFeature(FEATURES.ASSIGN_COMMITMENT), validate(assignCommitmentSchema), asyncHandler(assign));
commitmentsRouter.post("/:id/mark-delivered", requireAuth, asyncHandler(markDeliveredCtrl));
commitmentsRouter.post("/:id/send-approval-link", requireAuth, asyncHandler(sendApproval));
commitmentsRouter.post("/:id/resend-approval-link", requireAuth, asyncHandler(resendApproval));
commitmentsRouter.post("/:id/send-acceptance-link", requireAuth, asyncHandler(sendAcceptance));
commitmentsRouter.post("/:id/resend-acceptance-link", requireAuth, asyncHandler(resendAcceptance));
commitmentsRouter.get("/:id/history", requireAuth, authorizeFeature(FEATURES.APPROVAL_HISTORY), asyncHandler(history));
commitmentsRouter.get("/:id/change-requests", requireAuth, asyncHandler(authorizeCommitmentAccess), validate(listChangeRequestsSchema), asyncHandler(listChangeRequestsCtrl));
commitmentsRouter.post("/:id/change-requests/:changeRequestId/accept", requireAuth, asyncHandler(authorizeCommitmentAccess), validate(acceptChangeRequestSchema), asyncHandler(acceptChangeRequestCtrl));
commitmentsRouter.post("/:id/change-requests/:changeRequestId/reject", requireAuth, asyncHandler(authorizeCommitmentAccess), validate(rejectChangeRequestSchema), asyncHandler(rejectChangeRequestCtrl));
