export const FEATURES=Object.freeze({
  MANAGER_ROLE:"MANAGER_ROLE",
  ASSIGN_COMMITMENT:"ASSIGN_COMMITMENT",
  APPROVAL_HISTORY:"APPROVAL_HISTORY",
  ADVANCED_REPORTS:"ADVANCED_REPORTS",
  CSV_EXPORT:"CSV_EXPORT",
  BRANDED_PDF:"BRANDED_PDF",
  AUTO_REMINDERS:"AUTO_REMINDERS",
  CLIENT_PORTAL:"CLIENT_PORTAL",
});
