import { PLANS } from "./plans.js";
import { FEATURES } from "./features.js";
export const planRules=Object.freeze({
  [PLANS.AGENCY]: new Set([]),
  [PLANS.MID]: new Set([FEATURES.MANAGER_ROLE,FEATURES.ASSIGN_COMMITMENT,FEATURES.APPROVAL_HISTORY,FEATURES.ADVANCED_REPORTS,FEATURES.CSV_EXPORT]),
  [PLANS.PREMIUM]: new Set([FEATURES.MANAGER_ROLE,FEATURES.ASSIGN_COMMITMENT,FEATURES.APPROVAL_HISTORY,FEATURES.ADVANCED_REPORTS,FEATURES.CSV_EXPORT,FEATURES.BRANDED_PDF,FEATURES.AUTO_REMINDERS,FEATURES.CLIENT_PORTAL]),
});
