export const COMMITMENT_STATUS=Object.freeze({
  DRAFT:"DRAFT",
  INTERNAL_REVIEW:"INTERNAL_REVIEW",
  AWAITING_CLIENT_APPROVAL:"AWAITING_CLIENT_APPROVAL",
  IN_PROGRESS:"IN_PROGRESS",
  CHANGE_REQUEST_CREATED:"CHANGE_REQUEST_CREATED",
  DELIVERED:"DELIVERED",
  ACCEPTED:"ACCEPTED",
  CLOSED:"CLOSED",
  CANCELLED:"CANCELLED",
});
export const LINK_PURPOSE=Object.freeze({ APPROVAL:"APPROVAL", ACCEPTANCE:"ACCEPTANCE" });
